[project]
name = "dumbucket"
version = "0.1.0"
description = "An file bucket with SSRF vulnerability"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "pycurl>=7.45.7",
]
